### ISSUE TITLE
Mono repository incorrectly reporting success

### ISSUE THREAD

**Issue by awentzel** [paambaati/codeclimate-action#169]
**Is your feature request related to a problem? Please describe.**
When running the following GitHub Action on a Lerna mono-repository if any single package fails, it still reports success. 

In my example, the projectRoot incorrectly pointed to `../../../` instead of below code block, causing format_coverage to break, yet GH Action codeclimate-action to report success though really fail.
```bash
    "coverageReporters": [
      "json", 
      [
        "lcov", {"projectRoot": "../../"}
      ]
    ],
```

**Describe the solution you'd like**
Accurately report status as success and see that through on the Code Climate settings test reporting pages.

**Additional context**

**Comment by wagenet** [comment]
I'm seeing something similar though my scenario is a bit simpler.
Here are my logs:
```
2020-05-06T22:52:09.8261414Z [command]/__w/skylight-rust/skylight-rust/cc-reporter format-coverage /__w/skylight-rust/skylight-rust/coverage/lcov.info -t lcov -o codeclimate.0.json
2020-05-06T22:52:09.8338360Z fatal: Not a git repository (or any parent up to mount point /__w)
2020-05-06T22:52:09.8339052Z Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2020-05-06T22:52:09.8342532Z Error: exit status 128
2020-05-06T22:52:09.8352365Z Usage:
2020-05-06T22:52:09.8352933Z   cc-test-reporter format-coverage [coverage file] [flags]
2020-05-06T22:52:09.8353035Z 
2020-05-06T22:52:09.8353169Z Flags:
2020-05-06T22:52:09.8353469Z       --add-prefix string   add this prefix to file paths
2020-05-06T22:52:09.8353874Z   -t, --input-type string   type of input source to use [clover, cobertura, coverage.py, excoveralls, gcov, gocov, jacoco, lcov, simplecov, xccov]
2020-05-06T22:52:09.8354218Z   -o, --output string       output path (default "coverage/codeclimate.json")
2020-05-06T22:52:09.8354631Z   -p, --prefix string       the root directory where the coverage analysis was performed (default "/__w/skylight-rust/skylight-rust")
2020-05-06T22:52:09.8354743Z 
2020-05-06T22:52:09.8354875Z Global Flags:
2020-05-06T22:52:09.8355144Z   -d, --debug   run in debug mode
2020-05-06T22:52:09.8355229Z 
2020-05-06T22:52:09.8379983Z (node:823) UnhandledPromiseRejectionWarning: TypeError: (s || "").replace is not a function
2020-05-06T22:52:09.8380659Z     at escapeData (/__w/_actions/paambaati/codeclimate-action/v2.6.0/node_modules/@actions/core/lib/command.js:66:10)
```

**Comment by pierre-emmanuelJ** [comment]
I got something similar with go coverage.
```
Shell
Flags:
  -s, --batch-size int               batch size for source files (default 500)
  -e, --coverage-endpoint string     endpoint to upload coverage information to (default "https://api.codeclimate.com/v1/test_reports")
  -t, --coverage-input-type string   type of input source to use [clover, cobertura, coverage.py, excoveralls, gcov, gocov, jacoco, lcov, simplecov, xccov]
      --exit-code int                exit code of the test run
  -r, --id string                    reporter identifier
      --insecure                     send coverage insecurely (without HTTPS)
  -p, --prefix string                the root directory where the coverage analysis was performed (default "/home/runner/work/egoscale/egoscale")

Global Flags:
  -d, --debug   run in debug mode

(node:3245) UnhandledPromiseRejectionWarning: TypeError: (s || "").replace is not a function
    at escapeData (/home/runner/work/_actions/paambaati/codeclimate-action/v2.6.0/node_modules/@actions/core/lib/command.js:66:10)
    at Command.toString (/home/runner/work/_actions/paambaati/codeclimate-action/v2.6.0/node_modules/@actions/core/lib/command.js:60:35)
    at issueCommand (/home/runner/work/_actions/paambaati/codeclimate-action/v2.6.0/node_modules/@actions/core/lib/command.js:23:30)
    at Object.issue (/home/runner/work/_actions/paambaati/codeclimate-action/v2.6.0/node_modules/@actions/core/lib/command.js:27:5)
    at Object.error (/home/runner/work/_actions/paambaati/codeclimate-action/v2.6.0/node_modules/@actions/core/lib/core.js:127:15)
    at /home/runner/work/_actions/paambaati/codeclimate-action/v2.6.0/lib/main.js:189:20
    at Generator.throw (<anonymous>)
    at rejected (/home/runner/work/_actions/paambaati/codeclimate-action/v2.6.0/lib/main.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:3245) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3245) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by paambaati** [comment]
Can you folks try out the latest [`v2.7.0`](https://github.com/paambaati/codeclimate-action/releases/tag/v2.7.0) release? It has better error handling and should help you pinpoint issues better.

**Comment by KillyMXI** [comment]
I think I got a very relate issue.

coverage action:

```yml
      - name: Publish coverage results
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run cover
          coverageLocations: |
            ${{github.workspace}}/packages/html-to-text/coverage/lcov.info:lcov
          debug: true
```

Error report:

```
/home/runner/work/node-html-to-text/node-html-to-text/cc-reporter format-coverage 
/home/runner/work/node-html-to-text/node-html-to-text/packages/html-to-text/coverage/lcov.info -t lcov -o codeclimate.0.json --debug
time="2021-11-14T17:16:46Z" level=debug msg="coverage path /home/runner/work/node-html-to-text/node-html-to-text/packages/html-to-text/coverage/lcov.info" 
time="2021-11-14T17:16:46Z" level=debug msg="using formatter lcov" 
time="2021-11-14T17:16:46Z" level=debug msg="checking search path /home/runner/work/node-html-to-text/node-html-to-text/packages/html-to-text/coverage/lcov.info for lcov formatter" 
time="2021-11-14T17:16:48Z" level=debug msg="couldn't load committed at from ENV, trying git..." 
time="2021-11-14T17:16:48Z" level=info msg="trimming with prefix /home/runner/work/node-html-to-text/node-html-to-text/" 
time="2021-11-14T17:16:48Z" level=debug msg="getting fallback blob_id for source file src/formatter.js" 
time="2021-11-14T17:16:48Z" level=error msg="failed to read file src/formatter.js\nopen src/formatter.js: no such file or directory" 
Error: open src/formatter.js: no such file or directory
```

There is a misformed message in the next to last line:

```
msg="failed to read file src/formatter.js\nopen src/formatter.js: no such file or directory" 
```

But what I think is the actual cause of the issue:
The action seems to be looking for source files from the root or the repository.
This is just not true for a monorepo.
And I can't provide a custom prefix because it has to be different for each package. That is, each coverage location has it's own prefix.
