### ISSUE TITLE
Error: could not find any viable formatter 255

### ISSUE THREAD

**Issue by sergeevpasha** [paambaati/codeclimate-action#316]
**Describe the bug**
Getting an error on after-build (never saw this command running in 2.7.1 and earlier):
```
Error: could not find any viable formatter. available formatters: clover, cobertura, coverage.py, excoveralls, gcov, gocov, jacoco, lcov, lcov-json, simplecov, xccov
Usage:
  cc-test-reporter after-build [flags]
```

**Version of `codeclimate-action` you're using**
`v2.7.5`

**Expected behavior**
2.7.1 an earlier versions used to work perfectly. Now I just have no clue what to do. Is that some kind of general CC change and I have to change the config, or is that just a bug? Switched to 2.7.1 atm

**Additional context**
My GitHub Actions cc config:

     - name: Code Test and Coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: "${{secrets.CC_TEST_REPORTER_ID}}"
        with:
          coverageCommand: composer test-cover
          coverageLocations: "${{github.workspace}}/coverage.xml:clover"

**Comment by sergeevpasha** [comment]
any news?

**Comment by rap2hpoutre** [comment]
Any news?

**Comment by paambaati** [comment]
Can you please include a link to the failing run?

**Comment by drzraf** [comment]
Same issue. `cc-test-reporter after-build` is expecting some mandatory parameter that `codeclimate-action` is not passing.

**Comment by paambaati** [comment]
Please include a link to the failing run, along with the `debug` flag turned on, and I'd be happy to look into this issue.

**Comment by sergeevpasha** [comment]
@paambaati hey, received update v3 and there is a new error now
https://github.com/sergeevpasha/laravel-dpd/pull/31/checks?check_run_id=3746560589

**Comment by paambaati** [comment]
@sergeevpasha Can you re-run it? There was a brief period where v3.x was broken (see https://github.com/paambaati/codeclimate-action/issues/430) and was fixed and re-released.

**Comment by Thorin0ak** [comment]
I had to downgrade to 2.7.1 to get it to work.

**Comment by ChinmayaNathany** [comment]
Same, I had to downgrade to 2.7.1 too

**Comment by paambaati** [comment]
Closing this, as there's no recent comments with relevant links.

**Comment by ericpyle** [comment]
@paambaati I had the same issue as others here.  In my case, I have jobs that generate the lcov.info files, so I just need to publish those.

Here is my coverage step in my `deploy.yml`:
```
    name: Publish Code Coverage to CodeClimate
    runs-on: ubuntu-latest
    steps:
    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      with:
        debug: true
        coverageLocations: |
          ${{github.workspace}}/backend/services/tests/coverage/lcov.info:lcov
          ${{github.workspace}}/frontend/src/tests/coverage/lcov.info:lcov
```

Here are my github action logs (sorry that I don't have a public link).

Setup Job
``` 
2022-09-27T21:15:27.2435658Z Current runner version: '2.296.2'
2022-09-27T21:15:27.2466256Z ##[group]Operating System
2022-09-27T21:15:27.2466988Z Ubuntu
2022-09-27T21:15:27.2467719Z 20.04.5
2022-09-27T21:15:27.2468095Z LTS
2022-09-27T21:15:27.2468447Z ##[endgroup]
2022-09-27T21:15:27.2468765Z ##[group]Runner Image
2022-09-27T21:15:27.2469279Z Image: ubuntu-20.04
2022-09-27T21:15:27.2469655Z Version: 20220922.2
2022-09-27T21:15:27.2470231Z Included Software: https://github.com/actions/runner-images/blob/ubuntu20/20220922.2/images/linux/Ubuntu2004-Readme.md
2022-09-27T21:15:27.2470899Z Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20220922.2
2022-09-27T21:15:27.2471492Z ##[endgroup]
2022-09-27T21:15:27.2471897Z ##[group]Runner Image Provisioner
2022-09-27T21:15:27.2472304Z 1.0.0.0-main-20220916-1
2022-09-27T21:15:27.2472612Z ##[endgroup]
2022-09-27T21:15:27.2473766Z ##[group]GITHUB_TOKEN Permissions
2022-09-27T21:15:27.2474483Z Actions: write
2022-09-27T21:15:27.2474862Z Checks: write
2022-09-27T21:15:27.2475568Z Contents: write
2022-09-27T21:15:27.2475897Z Deployments: write
2022-09-27T21:15:27.2476277Z Discussions: write
2022-09-27T21:15:27.2476639Z Issues: write
2022-09-27T21:15:27.2477012Z Metadata: read
2022-09-27T21:15:27.2477365Z Packages: write
2022-09-27T21:15:27.2477729Z Pages: write
2022-09-27T21:15:27.2478096Z PullRequests: write
2022-09-27T21:15:27.2478484Z RepositoryProjects: write
2022-09-27T21:15:27.2483003Z SecurityEvents: write
2022-09-27T21:15:27.2483540Z Statuses: write
2022-09-27T21:15:27.2484302Z ##[endgroup]
2022-09-27T21:15:27.2488582Z Secret source: Actions
2022-09-27T21:15:27.2489262Z Prepare workflow directory
2022-09-27T21:15:27.3802994Z Prepare all required actions
2022-09-27T21:15:27.4036396Z Getting action download info
2022-09-27T21:15:27.6636734Z Download action repository 'paambaati/codeclimate-action@v3.0.0' (SHA:84cea27117a473d605400ca3a97fcef7e433e2d6)
```
Publish code coverage:
```
2022-09-27T21:15:30.5213445Z ##[group]Run paambaati/codeclimate-action@v3.0.0
2022-09-27T21:15:30.5214003Z with:
2022-09-27T21:15:30.5214231Z   debug: true
2022-09-27T21:15:30.5214753Z   coverageLocations: /home/runner/work/library.bible/library.bible/backend/services/tests/coverage/lcov.info:lcov
/home/runner/work/library.bible/library.bible/frontend/src/tests/coverage/lcov.info:lcov

2022-09-27T21:15:30.5215280Z   verifyDownload: true
2022-09-27T21:15:30.5215518Z env:
2022-09-27T21:15:30.5215749Z   AWS_DEFAULT_REGION: us-west-2
2022-09-27T21:15:30.5216480Z   CC_TEST_REPORTER_ID: ***
2022-09-27T21:15:30.5216753Z ##[endgroup]
2022-09-27T21:15:35.0454669Z [command]/home/runner/work/library.bible/library.bible/cc-reporter before-build
2022-09-27T21:15:35.0556980Z ℹ️ 'coverageCommand' not set, so skipping building coverage report!
2022-09-27T21:15:35.0634847Z [command]/home/runner/work/library.bible/library.bible/cc-reporter after-build --exit-code 0 --debug
2022-09-27T21:15:35.0696182Z time="2022-09-27T21:15:35Z" level=debug msg="about to run format-coverage" 
2022-09-27T21:15:35.0697440Z time="2022-09-27T21:15:35Z" level=debug msg="searching for a formatter to use" 
2022-09-27T21:15:35.0698311Z time="2022-09-27T21:15:35Z" level=debug msg="checking coverage.py formatter" 
2022-09-27T21:15:35.0699437Z time="2022-09-27T21:15:35Z" level=debug msg="checking search path coverage.xml for coverage.py formatter" 
2022-09-27T21:15:35.0700539Z time="2022-09-27T21:15:35Z" level=debug msg="checking excoveralls formatter" 
2022-09-27T21:15:35.0701877Z time="2022-09-27T21:15:35Z" level=debug msg="checking search path cover/excoveralls.json for excoveralls formatter" 
2022-09-27T21:15:35.0702613Z time="2022-09-27T21:15:35Z" level=debug msg="checking lcov formatter" 
2022-09-27T21:15:35.0703200Z time="2022-09-27T21:15:35Z" level=debug msg="checking search path coverage/lcov.info for lcov formatter" 
2022-09-27T21:15:35.0704087Z time="2022-09-27T21:15:35Z" level=debug msg="checking lcov-json formatter" 
2022-09-27T21:15:35.0704590Z time="2022-09-27T21:15:35Z" level=debug msg="checking simplecov formatter" 
2022-09-27T21:15:35.0705189Z time="2022-09-27T21:15:35Z" level=debug msg="checking search path coverage/coverage.json for simplecov formatter" 
2022-09-27T21:15:35.0706287Z time="2022-09-27T21:15:35Z" level=debug msg="checking search path coverage/.resultset.json for simplecov formatter" 
2022-09-27T21:15:35.0706854Z time="2022-09-27T21:15:35Z" level=debug msg="checking clover formatter" 
2022-09-27T21:15:35.0707877Z time="2022-09-27T21:15:35Z" level=debug msg="checking search path build/logs/clover.xml for clover formatter" 
2022-09-27T21:15:35.0708787Z time="2022-09-27T21:15:35Z" level=debug msg="checking search path clover.xml for clover formatter" 
2022-09-27T21:15:35.0709421Z time="2022-09-27T21:15:35Z" level=debug msg="checking gcov formatter" 
2022-09-27T21:15:35.0710081Z time="2022-09-27T21:15:35Z" level=debug msg="checking search path ./ for GCov formatter" 
2022-09-27T21:15:35.0714036Z time="2022-09-27T21:15:35Z" level=debug msg="checking gocov formatter" 
2022-09-27T21:15:35.0714776Z time="2022-09-27T21:15:35Z" level=debug msg="checking search path c.out for gocov formatter" 
2022-09-27T21:15:35.0715299Z time="2022-09-27T21:15:35Z" level=debug msg="checking jacoco formatter" 
2022-09-27T21:15:35.0715986Z time="2022-09-27T21:15:35Z" level=debug msg="checking search path jacoco.xml for jacoco formatter" 
2022-09-27T21:15:35.0716514Z time="2022-09-27T21:15:35Z" level=debug msg="checking xccov formatter" 
2022-09-27T21:15:35.0717073Z time="2022-09-27T21:15:35Z" level=debug msg="checking search path coverage.json for xccov formatter" 
2022-09-27T21:15:35.0717705Z time="2022-09-27T21:15:35Z" level=debug msg="checking cobertura formatter" 
2022-09-27T21:15:35.0718264Z time="2022-09-27T21:15:35Z" level=debug msg="checking search path cobertura.xml for cobertura formatter" 
2022-09-27T21:15:35.0719022Z Error: could not find any viable formatter. available formatters: clover, cobertura, coverage.py, excoveralls, gcov, gocov, jacoco, lcov, lcov-json, simplecov, xccov
2022-09-27T21:15:35.0719987Z Usage:
2022-09-27T21:15:35.0720295Z   cc-test-reporter after-build [flags]
2022-09-27T21:15:35.0720475Z 
2022-09-27T21:15:35.0720547Z Flags:
2022-09-27T21:15:35.0721057Z   -s, --batch-size int               batch size for source files (default 500)
2022-09-27T21:15:35.0721772Z   -e, --coverage-endpoint string     endpoint to upload coverage information to (default "https://api.codeclimate.com/v1/test_reports")
2022-09-27T21:15:35.0722589Z   -t, --coverage-input-type string   type of input source to use [clover, cobertura, coverage.py, excoveralls, gcov, gocov, jacoco, lcov, lcov-json, simplecov, xccov]
2022-09-27T21:15:35.0723149Z       --exit-code int                exit code of the test run
2022-09-27T21:15:35.0724223Z   -r, --id string                    reporter identifier (default "***")
2022-09-27T21:15:35.0724713Z       --insecure                     send coverage insecurely (without HTTPS)
2022-09-27T21:15:35.0725327Z   -p, --prefix string                the root directory where the coverage analysis was performed (default "/home/runner/work/library.bible/library.bible")
2022-09-27T21:15:35.0725640Z 
2022-09-27T21:15:35.0725724Z Global Flags:
2022-09-27T21:15:35.0726133Z   -d, --debug   run in debug mode
2022-09-27T21:15:35.0726285Z 
2022-09-27T21:15:35.0761655Z ##[error]The process '/home/runner/work/library.bible/library.bible/cc-reporter' failed with exit code 255
2022-09-27T21:15:35.0771787Z ##[error]🚨 CC Reporter after-build checkin failed!
2022-09-27T21:15:35.0773607Z (node:1521) UnhandledPromiseRejectionWarning: Error: The process '/home/runner/work/library.bible/library.bible/cc-reporter' failed with exit code 255
2022-09-27T21:15:35.0774372Z     at ExecState._setResult (/home/runner/work/_actions/paambaati/codeclimate-action/v3.0.0/node_modules/@actions/exec/lib/toolrunner.js:592:25)
2022-09-27T21:15:35.0775075Z     at ExecState.CheckComplete (/home/runner/work/_actions/paambaati/codeclimate-action/v3.0.0/node_modules/@actions/exec/lib/toolrunner.js:575:18)
2022-09-27T21:15:35.0775973Z     at ChildProcess.<anonymous> (/home/runner/work/_actions/paambaati/codeclimate-action/v3.0.0/node_modules/@actions/exec/lib/toolrunner.js:469:27)
2022-09-27T21:15:35.0777498Z     at ChildProcess.emit (events.js:314:20)
2022-09-27T21:15:35.0777851Z     at maybeClose (internal/child_process.js:1022:16)
2022-09-27T21:15:35.0778258Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
2022-09-27T21:15:35.0782710Z (node:1521) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
2022-09-27T21:15:35.0784149Z (node:1521) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I thought that going back to `v2.7.1` fixed it like others have said, but looking at the logs, I can't tell that it's doing anything, but I don't see any errors:

```
2022-09-27T21:28:00.1253242Z ##[group]Run paambaati/codeclimate-action@v2.7.1
2022-09-27T21:28:00.1253658Z with:
2022-09-27T21:28:00.1253956Z   debug: true
2022-09-27T21:28:00.1254516Z   coverageLocations: /home/runner/work/library.bible/library.bible/backend/services/tests/coverage/lcov.info:lcov
/home/runner/work/library.bible/library.bible/frontend/src/tests/coverage/lcov.info:lcov

2022-09-27T21:28:00.1255070Z   coverageCommand: yarn coverage
2022-09-27T21:28:00.1255355Z env:
2022-09-27T21:28:00.1255653Z   AWS_DEFAULT_REGION: us-west-2
2022-09-27T21:28:00.1256326Z   CC_TEST_REPORTER_ID: ***
2022-09-27T21:28:00.1256641Z ##[endgroup]
```

**Comment by ericpyle** [comment]
> @paambaati I had the same issue as others here. In my case, I have jobs that generate the lcov.info files, so I just need to publish those.
> 
> Here is my coverage step in my `deploy.yml`:
> 
> ```
>     name: Publish Code Coverage to CodeClimate
>     runs-on: ubuntu-latest
>     steps:
>     - name: Publish code coverage
>       uses: paambaati/codeclimate-action@v3.0.0
>       env:
>         CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
>       with:
>         debug: true
>         coverageLocations: |
>           ${{github.workspace}}/backend/services/tests/coverage/lcov.info:lcov
>           ${{github.workspace}}/frontend/src/tests/coverage/lcov.info:lcov
> ```
...
> 2022-09-27T21:15:35.0719022Z Error: could not find any viable formatter. available formatters: clover, cobertura, coverage.py, excoveralls, gcov, gocov, jacoco, lcov, lcov-json, simplecov, xccov
> ```

Okay, I suspect in my case it was because the `lcov.info` files (in coverageLocations) did not exist on disk because they only existed in the context of an earlier github job that ran those tests. When I moved the coverage step inside the test job, I no longer got this error.

@paambaati, I guess the change request would be to have a more helpful message in case the coverage files are not located in this context?

**Comment by paambaati** [comment]
@ericpyle Definitely. The CodeClimate reporter can print a better error message, as it is the one reading and parsing coverage files.

This action is simply a thin wrapper around the reporter, and only executes it with a few parameters.
