### ISSUE TITLE
Error upon trying to use Action

### ISSUE THREAD

**Issue by exoRift** [paambaati/codeclimate-action#584]
**Describe the bug**
When trying to use this action, I get an error. Happened when I upgraded to v3. Never had it before

**Version of `codeclimate-action` you're using**
`v3`

**Example links**
[Workflow File](https://github.com/exoRift/mass-require/blob/master/.github/workflows/quality_assurance.yml)

```
Download action repository 'paambaati/codeclimate-action@v3' (SHA:e5d7b870aec2c3faa8249ec2444850f153c6ccef)
Error: paambaati/codeclimate-action/v3/action.yml:
Error: paambaati/codeclimate-action/v3/action.yml: (Line: 30, Col: 51, Idx: 902) - (Line: 30, Col: 80, Idx: 931): While parsing a block mapping, did not find expected key.
Error: System.ArgumentException: Unexpected type '' encountered while reading 'action manifest root'. The type 'MappingToken' was expected.
   at GitHub.DistributedTask.ObjectTemplating.Tokens.TemplateTokenExtensions.AssertMapping(TemplateToken value, String objectDescription)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load paambaati/codeclimate-action/v3/action.yml
```

**Comment by paambaati** [comment]
Not a bug; see https://github.com/paambaati/codeclimate-action/issues/577#issuecomment-1188527480
